### ISSUE TITLE
DQ200 6R挡换挡拨叉更换课程于测试服务器问题  2019.10.22

### ISSUE THREAD

**Issue by zhangerniu877** [i-fuyun/custom-course-frame#11]
DQ200 6R挡换挡拨叉更换课程于测试服务器上，测试时发现的问题
![image](https://user-images.githubusercontent.com/51052512/67348111-7c305880-f576-11e9-8279-89ea53435037.png)

问题1：进入该页面，点击“进入”后，会出现如图中弹出来的警告画面。但，点击警告页面中的“是或否”后，警告页面消失，课程可继续往下进行操作。
![image](https://user-images.githubusercontent.com/51052512/67348133-8a7e7480-f576-11e9-8def-8c86d4f63728.png)

问题2：一进入该页面，即弹出如图中的警告页面（此时未进行任何操作）。但，点击警告页面中的“是或否”后，警告页面消失，课程可继续往下进行操作。
![image](https://user-images.githubusercontent.com/51052512/67348140-910cec00-f576-11e9-80e0-0c38488f8545.png)

问题3：当操作课程的测试部分时，在操作至安装卡环盖罩之后，会弹出如上图的界面，点击关闭该界面之后，待刷新后（刷新时间较长）可继续向下操作（但有时会直接退出测试平台）。
![image](https://user-images.githubusercontent.com/51052512/67348149-99652700-f576-11e9-9d1b-6465a50efca2.png)

问题4：安装完黄色箭头所示的螺栓后，会弹出如图所示的界面，点击关闭后，画面在刷新后会直接跳入下一界面，而当前界面中红色箭头所示的螺栓并未安装。
![image](https://user-images.githubusercontent.com/51052512/67348156-a1bd6200-f576-11e9-9a32-c2b4c66ae6bf.png)

问题5：点击“提交”后，也会弹出如上图的警告文字框，点击警告页面中的“是或否”后，警告页面消失，课程可继续往下进行操作。
![image](https://user-images.githubusercontent.com/51052512/67348170-a8e47000-f576-11e9-8d99-72b0bf946aae.png)

问题6：此处得分是有问题的，因为问题四中有一步是没有操作的，所以不应该是满分。另外，画红框处在做完测试后应是有进度的（如100%），而不是0%.

**Comment by i-fuyun** [comment]
[DQ200 6R挡换挡拨叉更换课程于测试服务器 测试发现问题 2019.10.24.docx](https://github.com/i-fuyun/custom-course-frame/files/3765986/DQ200.6R.2019.10.24.docx)

协助解决上面提出的问题；

**Comment by i-fuyun** [comment]
问题汇总：
1. 弹错误提示框的原因
解决方案：是网页和本地客户端穿数据的接口，一直是以前的写法，在传送数据前会检测此接口是否存在，现在客户端会报错，屏蔽接口检测写法；

2. 动画操作不了的问题
解决方案：未重现文档上显示的问题，推测 是客户端所在电脑太卡，内存不够导致的？可以再测试试试。

3.进度不显示的问题：
解决方案： 原先课件的 进度一般是 子页面内容资源学完才给进度的；现在课件测试没有得100分，所以没有进度；
                   现在进行特殊处理，让 课件添加规则：如果是虚拟拆装类动画，此动画的进度=config表上此动画分配的进度值*(拆装测试得分/100)，这个规则进度计算；
