### ISSUE TITLE
DQ200-课件包相关修改意见 2019072916

### ISSUE THREAD

**Issue by liaoxiangfeng12345678** [i-fuyun/custom-course-frame#8]
功能及问题修改如下：
一、菜单页及滚动条修改。
       修改：写自定义的滚动条组件程序。要求只滚动 菜单项，菜单页的标题固定。滚动条的皮肤可换成ui设计的那种，箭头按钮可以始终保证初始化时位置，菜单页的打开，关闭触发方式可随意设定mouseover。
二、按钮图片变形。
       修改：需要调整调用外部图片的控件的大小，让控件大小和图片大小比例保持一致，在动画中修改。
三、点击“进入”后，闪现出现按钮栏问题。
       修改：依据发布的课件包，进行检查并修改。按钮栏的出现，应在点击并进入某项选项（演示、练下、测试）后再出现。
四、进入测试后，其按钮栏显示问题。
       修改：点击“测试”，进入测试后，其右侧按钮栏显示的状态应是默认出现。
五、按钮栏的间距调整。
       修改：使用修改后最新UI（按钮栏的间距已调整），替换现在UI中的按钮栏。
[DQ200-课件包相关修改意见 2019.7.29.docx](https://github.com/i-fuyun/custom-course-frame/files/3439881/DQ200-.2019.7.29.docx)

**Comment by i-fuyun** [comment]
已修复。

**Comment by i-fuyun** [comment]
![FE3 S%E)JV1Y}@$%84I`ZF1](https://user-images.githubusercontent.com/5111701/62432220-1d222b00-b761-11e9-8c0d-14b3a6a083eb.png)

**Comment by i-fuyun** [comment]
1. 1.5day
2. 测试分数在actionStep表里，你们自己设置的
![~~J_2(WPQW$XR@UWA%O11F2](https://user-images.githubusercontent.com/5111701/62432275-670b1100-b761-11e9-90b8-8d956aab99d8.png)
3. 0.5day-1day
